apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: akl-api-gw-prod-cluster
  region: us-east-2


vpc:
  cidr: 10.16.0.0/16
  autoAllocateIPv6: true
  # disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: true
    privateAccess: true


managedNodeGroups:
  - name: akl-gw-ng-1
    privateNetworking: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    volumeSize: 20
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        certManager: true
        cloudWatch: true
    ssh:
    #allow ssh using public key this needs a bastion host since nodes are in private subnet
      #allow: true
      #publicKeyPath: ~/.ssh/akl-apigw.pem.pub
      enableSsm: true
       


cloudWatch:
  clusterLogging:
    enableTypes: ["*"]